---
title: "H5 Stage Export Exploration"
author: "Maddee Rubenson (FlowWest)"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

### Objective 

Compare scenario `FPV2Mb` to baseline `H1Z` daily summary values. Note that data was exported from the H5 here: https://github.com/FlowWest/sdg-dashboard/tree/hydro-exports


### Load H5 exports

#### FPV2Mb

```{r}
old_stage_export <- read_csv('data-raw/hdf5_exports/old_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "FPV2Mb") |> 
  glimpse()

dgl_stage_export <- read_csv('data-raw/hdf5_exports/dgl_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "FPV2Mb") |> 
  glimpse()

mho_stage_export <- read_csv('data-raw/hdf5_exports/mho_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "FPV2Mb") |> 
  glimpse()

```

#### Baseline

```{r}
base_old_stage_export <- read_csv('data-raw/hdf5_exports/old_baseline_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "baseline") |> 
  glimpse()

base_dgl_stage_export <- read_csv('data-raw/hdf5_exports/dgl_baseline_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "baseline") |> 
  glimpse()

base_mho_stage_export <- read_csv('data-raw/hdf5_exports/mho_baseline_stage_export.csv') |> 
  select(-`...1`) |> 
  mutate(scenario = "baseline") |> 
  glimpse()
```

```{r}
old_stage_export |> 
  ggplot() +
  geom_line(aes(x = Datetime, y = upstream_stage, color = "upstream")) +
  geom_line(aes(x = Datetime, y = downstream_stage, color = "downstream")) +
  theme_minimal() +
  ggtitle('OLD')

```

```{r}
dgl_stage_export |> 
  ggplot() +
  geom_line(aes(x = Datetime, y = downstream_stage, color = "downstream"), alpha = 0.5) +
  geom_line(aes(x = Datetime, y = upstream_stage, color = "upstream"), alpha = 0.5) +
  theme_minimal() + 
  ggtitle('DGL')

```

```{r}
mho_stage_export |> 
  ggplot() +
  geom_line(aes(x = Datetime, y = upstream_stage, color = "upstream")) +
  geom_line(aes(x = Datetime, y = downstream_stage, color = "downstream")) +
  theme_minimal() +
  ggtitle('MHO')

```
#### OLD Comparison to DSS Export 

```{r include=FALSE}
old_dss_export <- read_delim('data-raw/fpv2mb-old-stage.txt', 
                   delim = "\t",  
                   skip = 2,    
                   col_names = c("Index", "Datetime", "dss_stage_feet")) |> 
   mutate(
    Datetime = dmy_hm(Datetime)) |> 
  select(-Index) |> 
  glimpse()
```

```{r}
ggplot() + 
  geom_line(data = old_dss_export, aes(x = Datetime, y = dss_stage_feet, color = "DSS")) +
  geom_line(data = old_stage_export, aes(x = Datetime, y = upstream_stage, color = "H5 - upstream")) +
  geom_line(data = old_stage_export, aes(x = Datetime, y = downstream_stage, color = "H5 - downstream")) +
  theme_minimal() +
  ylab('stage')

```
## Get Stage Summaries

```{r}
all <- old_stage_export |> 
  full_join(dgl_stage_export) |> 
  full_join(mho_stage_export) |> 
  filter(Datetime >= "2020-01-01 00:00:00") |> # to align with baseline 
  full_join(base_old_stage_export) |> 
  full_join(base_mho_stage_export) |> 
  full_join(base_dgl_stage_export) |> 
  filter(Datetime <= "2024-01-01 00:00:00") |> 
  janitor::clean_names() |> 
  mutate(date = as.Date(datetime)) |> 
  group_by(date, channel_name, channel_id, scenario) |> 
  summarise(daily_avg = mean(c(upstream_stage, downstream_stage)),
            daily_min = min(c(upstream_stage, downstream_stage)),
            daily_max = max(c(upstream_stage, downstream_stage))) |> 
  glimpse()

```
### Compare to Baseline 

*comparison = daily min, max, or mean scenario - baseline*

```{r}
comparison <- all |> 
  pivot_wider(names_from = scenario,
    values_from = c(daily_avg, daily_min, daily_max)) |> 
  mutate(avg_daily_diff = daily_avg_FPV2Mb - daily_avg_baseline,
    min_daily_diff = daily_min_FPV2Mb - daily_min_baseline,
    max_daily_diff = daily_max_FPV2Mb - daily_max_baseline) |> 
  select(-c(daily_avg_FPV2Mb, daily_avg_baseline, daily_max_FPV2Mb, daily_min_baseline, daily_max_FPV2Mb, daily_max_baseline, daily_min_FPV2Mb))

comparison |> 
  na.omit() |> 
  ggplot() + 
  geom_line(aes(x = date, y = avg_daily_diff, color = "avg_daily_diff")) + 
  geom_line(aes(x = date, y = min_daily_diff, color = "min_daily_diff")) + 
  geom_line(aes(x = date, y = max_daily_diff, color = "max_daily_diff")) + 
  facet_wrap(~channel_name) + 
  ylab("stage difference (feet)")+
  theme_minimal()

```
```{r}
knitr::knit_exit()
```
### Interpolation? 

```{r}
# from h5 channel_output, maybe in feet? 
distance <- 1285

# Define inputs
upstream_stage <- 10.43  
downstream_stage <- 15 
distance <- 1285             
x <- distance/2                  

# Calculate the proportion
p <- x / distance

# Perform interpolation
interpolated_stage <- upstream_stage + p * (downstream_stage - upstream_stage)

```

# DGL

### H5 export

```{r}
old_stage_export <- read_csv('data-raw/hdf5_exports/old_stage_export.csv') |> 
  # mutate(output = "H5",
  #        diff = downstream_stage - upstream_stage) |> 
  select(-`...1`) |> 
  glimpse()
```

```{r}
old_stage_export |> 
  ggplot() +
  geom_line(aes(x = Datetime, y = upstream_stage, color = "upstream")) +
  geom_line(aes(x = Datetime, y = downstream_stage, color = "downstream")) +
  theme_minimal()

```

### DSS export 

```{r}
dgl_dss_export <- read_delim('data-raw/fpv2mb-dgl-stage.txt', 
                   delim = "\t",  
                   skip = 2,    
                   col_names = c("Index", "Datetime", "dss_stage_feet")) |> 
   mutate(
    Datetime = dmy_hm(Datetime)) |> 
  # mutate(model = "FPV2Mb",
  #        channel_name = "DGL",
  #        output = "DSS") |> 
  select(-Index) |> 
  glimpse()
```

### Compare

```{r}
ggplot() + 
  geom_line(data = dgl_dss_export, aes(x = Datetime, y = dss_stage_feet, color = "DSS")) +
  geom_line(data = old_stage_export, aes(x = Datetime, y = upstream_stage, color = "H5 - upstream")) +
  geom_line(data = old_stage_export, aes(x = Datetime, y = downstream_stage, color = "H5 - downstream")) +
  theme_minimal() +
  ylab('stage')

```

```{r}
merge <- old_dss_export |> 
  full_join(old_stage_export) |> 
  mutate(div = upstream_stage / dss_stage_feet,
         div2 = downstream_stage / dss_stage_feet,
         diff = downstream_stage - upstream_stage)


ggplot(merge, aes(x = upstream_stage, y = dss_stage_feet)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "red") +
  ggtitle("Relationship between DSS Stage Feet and Upstream Stage") +
  theme_minimal()


```

### Interpolation? 

```{r}
# from h5 channel_output, maybe in feet? 
distance <- 1285 # distance from upstream node to downstream node from channel_output; like a distance request becuase we want this distance downstream
length <- 5610 # length of the channel; from channel
prop <- 1285/5610 # proportion of that 1285 is of the entire channel 

# now look in xsect_layer to find the closest dist (0.227)
# values here are a function of how much water is in the channel 




# Define inputs
upstream_stage <- 10.43  
downstream_stage <- 15 
distance <- 1285             
x <- distance/2                  

# Calculate the proportion
p <- x / distance

# Perform interpolation
interpolated_stage <- upstream_stage + p * (downstream_stage - upstream_stage)

```
