---
title: "South Delta Gates - channel exploration"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: rows
  font_family: "Roboto Mono"
  google_fonts: true
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(DT)
library(RColorBrewer)
```

```{r}
# Read in scenarios 
combined_data_b1sa <- readRDS("data/combined_data_b1sa.RDS")
combined_data_b1sb <- readRDS("data/combined_data_b1sb.RDS")
combined_data_b1sa_stage <- readRDS("data/combined_STAGE_data_b1sa.rds")
combined_data_b1sb_stage <- readRDS("data/combined_STAGE_data_b1sb.rds")

all_data <- list(
  b1sa = list(EC = combined_data_b1sa, Stage = combined_data_b1sa_stage),
  b1sb = list(EC = combined_data_b1sb, Stage = combined_data_b1sb_stage)
)

# read in channel geometry
channels <- readRDS("data/channels_shp.RDS") |> 
  sf::st_transform(crs = 4326)

bbox <- st_bbox(channels)

gates <- channels |> 
  filter(id %in% c(71, 128, 205)) |> 
  mutate(name = case_when(id == 71 ~ "OLD", 
                          id == 128 ~ "MHO", 
                          id == 205 ~ "DGL")) |> 
  select(id, geometry, name) |> 
  distinct() 

```


## Inputs {.sidebar data-width="500"}

<!-- <!-- The scenario `FPV2Mb` is compared to the baseline, with  --> 

<!-- Difference values calculated as *scenario 1 - scenario 2*. -->

<!-- Each difference (min, max, mean) represents a comparison of the summarized values for a specific year, month with an option to summarize by month or day. Daily summaries are the summary of daily 5-minute increments. Monthly summarize represent the min, max, or mean of the daily summaries.  -->

```{r}
tabsetPanel(
  tabPanel("Map Controls", 
           
           tagList(
             tags$div(
               style = "display: inline-block; vertical-align: top; width: 45%;",
               selectInput("scen1", tags$strong("Scenario 1:"), 
                           choices = c("B1sa" = "b1sa", 
                                       "B1sb" = 'b1sb'),
                           selected = "b1sa")
             ),
             tags$div(
               style = "display: inline-block; vertical-align: top; width: 45%; margin-left: 5%;",
               selectInput("scen2", tags$strong("Scenario 2:"), 
                           choices = c("B1sa" = "b1sa", 
                                       "B1sb" = 'b1sb'),
                           selected = "b1sb")
             ),
             
             uiOutput("warning_message"),
             uiOutput("warning_message_2"),
             
             selectInput(inputId = "which_variable",
                         label = tags$strong("What Variable"),
                         choices = c("Stage", "EC"),
                         selected = "EC"),
             
             radioButtons(inputId = "which_agg", 
                          label = HTML("<strong>How to Summarize Data</strong>"),
                          choices = c("Daily", "Monthly"),
                          selected = "Daily"),
             
             selectInput(
               inputId = "which_year",
               label = HTML("<strong>Select Year</strong>"),
               choices = c(2020:2023), # TODO: this could be better and dynamically based off of the scenarios 
               selected = 2021
             ),
             
             
             sliderInput(
               inputId = "which_month",
               label = HTML("<strong>Select Month</strong>"),
               min = 5,
               max = 11,
               value = 5,
               step = 1,
               ticks = TRUE,
               animate = TRUE
             ),
             
             
             conditionalPanel(
               condition = "input.which_agg == 'Daily'",
               sliderInput(
                 inputId = "which_day", 
                 label = tags$strong("Select Day"),
                 min = 1, 
                 max = 30, # TODO: need to troubleshoot the 31 days so it doesn't crash
                 value = 1,
                 step = 1, 
                 ticks = TRUE, 
                 animate = TRUE
               )
             ),
             
             
             selectInput(
               inputId = "which_stat", 
               label = HTML("<strong>Select Statistic</strong>"),
               choices = c("Min", "Max", "Mean"), 
               selected = "Mean"
             ), 
             
             output$data_table <- renderDT({
               req(filtered_data())
               
               filtered_data() |>
                 st_set_geometry(NULL) |>
                 filter(id %in% c(71, 128, 205)) |>
                 mutate(name = case_when(id == 71 ~ "OLD",
                                         id == 128 ~ "MHO",
                                         id == 205 ~ "DGL")) |>
                 select(name, min_diff, avg_diff, max_diff) |>
                 mutate(
                   min_diff = round(min_diff, 3),
                   avg_diff = round(avg_diff, 3),
                   max_diff = round(max_diff, 3)
                 )
             }, options = list(
               searching = FALSE,
               lengthChange = FALSE,
               paging = FALSE,
               info = FALSE,
               scrollY = "150"
             )),
             
           )
           
           
           #----------------
  ), 
  tabPanel("Settings", 
           tagList(
             selectInput("color_palette", 
                         label="Select Color Palette", 
                         choices = c("Red to Blue"="RdBu", "Purple to Orange"="PuOr", "Purple to Green"="PRGn", "Red Yellow Green"="RdYlGn")), 
             
             sliderInput(inputId = "base_opacity", label = "Select base layer opacity", 
                         min = .5, max = 1, step = .1, value = 1)
           )),
  tabPanel("Data Processing",
           tags$iframe(src = "about.html", height = "100%", width = "100%", frameborder = "0")
           )
)



```

## Column {data-width="100" data-height="100"}

```{r}
scenario_1 <- reactive({input$scen1})
scenario_2 <- reactive({input$scen2})
which_variable <- reactive({input$which_variable})

scenario_1_data <- reactive({
  req(scenario_1())
  req(which_variable())
  all_data[[scenario_1()]][[which_variable()]] |> 
    as.data.frame() 
})

scenario_2_data <- reactive({
  req(scenario_2())
  req(which_variable())
  all_data[[scenario_2()]][[which_variable()]] |> 
    as.data.frame() 
})

output$warning_message <- renderUI({
  if (input$scen1 == input$scen2) {
    div(style = "color: darkred; font-weight: bold; font-size: 0.9em;",
        "Please select two different scenarios for comparison.")
  } else {
    NULL
  }
})

output$warning_message_2 <- renderUI({
  if (nrow(filtered_data()) == 0) {
    div(style = "color: darkred; font-weight: bold; font-size: 0.9em;",
        "There is no data for selected year and month; please select another")
  } else {
    NULL
  }
})

scenario_comparison <- reactive({
  req(c(input$scen1, input$scen2))
  
  validate(
    need(input$scen1 != input$scen2, "Please select two different scenarios for comparison.")
  )
  
  
  comparison <- bind_rows(scenario_1_data(), scenario_2_data()) |> 
    janitor::clean_names() |> 
    pivot_wider(
      names_from = scenario,
      values_from = c(daily_avg, daily_min, daily_max)
    ) |> 
    na.omit() 
  
  scenario_cols <- names(comparison)[grepl("^daily_avg_", names(comparison))]
  scenarios <- sub("^daily_avg_", "", scenario_cols)
  
  comparison <- comparison  |> 
    mutate(
      avg_diff = .data[[paste0("daily_avg_", scenarios[1])]] - .data[[paste0("daily_avg_", scenarios[2])]],
      min_diff = .data[[paste0("daily_min_", scenarios[1])]] - .data[[paste0("daily_min_", scenarios[2])]],
      max_diff = .data[[paste0("daily_max_", scenarios[1])]] - .data[[paste0("daily_max_", scenarios[2])]]
    ) 
  
  print("this is the return: ")
  comp_return <- comparison |>
    select(-contains("daily")) |> 
    mutate(month = lubridate::month(date),
           day = lubridate::day(date),
           year = lubridate::year(date)) |> 
    left_join(channels) |>
    glimpse()
  
  return(comp_return)
})

observe({
  req(input$scen1, input$scen2)
  
  comp <- scenario_comparison()
  
})


```

```{r}
filtered_data <- reactive({
  req(input$which_month, input$which_year, scenario_comparison())
  
  print(input$which_month)
  print(input$which_year)
  print(input$which_day)
  
  
  if(input$which_agg == "Monthly") {
    print("monthly")
    agg <- scenario_comparison() |>
      filter(month == input$which_month, 
             year == input$which_year) |> 
      group_by(month, id, year, geometry) |>
      summarize(min_diff = min(min_diff),
                max_diff = max(max_diff),
                avg_diff = mean(avg_diff)) |> 
      sf::st_as_sf() |> 
      ungroup()
    
    print(head(agg))
  } else {
    print("daily")
    agg <- scenario_comparison() |> 
      filter(day == input$which_day,
             month == input$which_month,
             year == input$which_year)  |> 
      st_as_sf()
  }
  
  validate(
    need(nrow(agg) > 0, "There is no data for selected year and month; please select another")
  )
  
  
  
  return(agg)
})

stat <- reactive({
  req(input$which_stat)
  
  switch(input$which_stat, 
         "Min" = 'min_diff', 
         "Max" = 'max_diff',
         "Mean" = 'avg_diff')
  
})

unit <- reactive({
  switch(input$which_variable,
         "Stage" = "feet",
         "EC" = "umhos/cm") # TODO: double check this
})

legend_title <- reactive({
  req(input$which_stat)
  
  switch(input$which_stat, 
         "Min" = paste0('Min Diff (', unit(), ")"), 
         "Max" = paste0('Max Diff (', unit(), ")"), 
         "Mean" = paste0('Mean Diff (', unit(), ")")
  ) 
  
})

output$map <- renderLeaflet({
  leaflet() |> 
    addTiles(urlTemplate = "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
             attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/">CARTO</a>', group = "Street", 
             options = tileOptions(opacity = input$base_opacity)) |> 
    addProviderTiles(
      "Esri.WorldImagery",
      group = "Satellite", 
      options = providerTileOptions(opacity = input$base_opacity)
    ) |>
    addProviderTiles(
      "USGS.USTopo",
      group = "Topographic",
      options = providerTileOptions(opacity = input$base_opacity)
    ) |>
    setView(lat = 37.82116120308882, lng = -121.42962730014777, zoom = 13  
    ) |> 
    addLayersControl(
      baseGroups = c("Satellite", "Street", "Topographic"),
      position = "topright",
      options = layersControlOptions(collapsed = FALSE)
    )
})

observe({
  req(filtered_data())
  
  print(head(filtered_data()))
  
  channels_merge <- filtered_data()
  current_stat <- stat()
  current_legend_title <- legend_title()
  
  # Define color palette
  data_min <- min(channels_merge$avg_diff, na.rm = TRUE)
  data_max <- max(channels_merge$avg_diff, na.rm = TRUE)
  # Determine the maximum absolute value
  max_abs_value <- range(channels_merge$avg_diff, channels_merge$min_diff, channels_merge$max_diff)
  
  palette <- colorNumeric(
    palette = colorRampPalette(brewer.pal(11, input$color_palette))(100),
    domain = c(-max_abs_value, max_abs_value))
  
  leafletProxy("map") |>
    clearShapes() |>
    clearControls() |>
    addPolylines(data = gates,
                 label = ~name,
                 labelOptions = labelOptions(permanent = TRUE,
                                             direction = "auto",
                                             opacity = 1,
                                             textOnly = FALSE,
                                             style = list(
                                               "font-weight" = "bold",
                                               "font-size" = "14px",
                                               "color" = "black",
                                               "background" = "white",
                                               "border" = "1px solid black",
                                               "padding" = "3px"
                                             ))) |>
    addPolylines(
      data = channels_merge,
      weight = 7,
      opacity = 1,
      label = ~as.character(id),
      color = ~palette(get(current_stat)),
      popup = ~sprintf(
        "<div style='font-family: Arial; font-size: 12px;'>
        <table style='width: 100%%; border-collapse: collapse; margin: 10px 0;'>
          <tr style='background-color: #f8f9fa;'>
            <td style='padding: 8px; border: 1px solid #dee2e6;'><strong>ID</strong></td>
            <td style='padding: 8px; border: 1px solid #dee2e6;'>%s</td>
          </tr>
          <tr style='background-color: #f8f9fa;'>
            <td style='padding: 8px; border: 1px solid #dee2e6;'><strong>%s</strong></td>
            <td style='padding: 8px; border: 1px solid #dee2e6;'>%.2f</td> 
          </tr>
        </table>
      </div>",
      as.character(id), current_legend_title, get(current_stat)
      ),
      labelOptions = labelOptions(
        style = list(
          "font-weight" = "bold",
          padding = "3px 8px"
        ),
        textsize = "15px",
        direction = "auto"
      )
    ) |>
    addLegend(
      position = "bottomright",
      pal = palette,
      values = channels_merge[[current_stat]],
      title = current_legend_title,
      opacity = 1
    )
})

leafletOutput("map", width = "100%", height = "100%")

```

